# Generated by Django 3.2.4 on 2021-06-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMEI',
            fields=[
                ('number', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
    ]
